micronaut:
  application:
    name: micronaut_image_test
  server:
    cors:
      enabled: true
    maxRequestSize: 100MB
    max-request-size: 100MB
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      maxFileSize: 100MB
      maxRequestSize: 100MB
      enabled: true
